//******************************************************************
// 
//  Generated by IDL to C++ Translator
//  
//  File name: GSDFPacket.h
//  Source: GSDFPacket.idl
//  Generated: Tue Nov 28 13:14:39 2017
//  OpenSplice V6.4.140407OSS
//  
//******************************************************************
#ifndef _GSDFPACKET_H_
#define _GSDFPACKET_H_

#include "sacpp_mapping.h"
#include "sacpp_DDS_DCPS.h"


namespace opensplice_dds_broker
{
   struct GSDFPacket;
   struct CharSeq_uniq_ {};
   typedef DDS_DCPSUFLSeq < DDS::Char, struct CharSeq_uniq_> CharSeq;
   typedef DDS_DCPSSequence_var < CharSeq> CharSeq_var;
   typedef DDS_DCPSSequence_out < CharSeq> CharSeq_out;

   struct GSDFPacket
   {
         CharSeq data;
   };

   typedef DDS_DCPSStruct_var < GSDFPacket> GSDFPacket_var;
   typedef DDS_DCPSStruct_out < GSDFPacket> GSDFPacket_out;
}




#endif 
