//******************************************************************
// 
//  Generated by IDL to C++ Translator
//  
//  File name: MSFPPacket.cpp
//  Source: MSFPPacket.idl
//  Generated: Thu Jul  7 23:28:06 2016
//  OpenSplice V6.4.140407OSS
//  
//******************************************************************

#include "MSFPPacket.h"




