//******************************************************************
// 
//  Generated by IDL to C++ Translator
//  
//  File name: GSDFPacket.h
//  Source: GSDFPacket.idl
//  Generated: Wed May 17 22:13:07 2017
//  OpenSplice V6.4.140407OSS
//  
//******************************************************************
#ifndef _GSDFPACKET_H_
#define _GSDFPACKET_H_

#include "sacpp_mapping.h"
#include "sacpp_DDS_DCPS.h"


namespace opensplice_dds_comm
{
   struct GSDFPacket;

   struct GSDFPacket
   {
         DDS::Long packet_source;
         DDS::UShort packet_version;
         DDS::UShort packet_type;
         DDS::String_mgr packet_data;
         DDS::LongLong package_check_sum;
   };

   typedef DDS_DCPSStruct_var < GSDFPacket> GSDFPacket_var;
   typedef DDS_DCPSStruct_out < GSDFPacket> GSDFPacket_out;
}




#endif 
