
module opensplice_dds_comm{

    struct GSDFPacket {
        long packet_source;
        unsigned short packet_version;
        unsigned short packet_type;
        string packet_data;
        long long package_check_sum;
    };
  #pragma keylist GSDFPacket
};
